connectionString = "postgres://soqsdloojpmgqg:12c9837fed213a64e07103c515a2a57d6bfce59de2e538e9e9a0ffce8e537dea@ec2-107-21-255-2.compute-1.amazonaws.com:5432/d91bbjvd9k9lg3"
path = "plugins/postgresql"
version = 0.1

[[dependencies]]
module = "pg"
version = "6.1.0"